---
app_name: prodigy
application_url: https://prodigy.cdh.princeton.edu

python_version: "3.12"
# single deploy path - no versioning, no nesting
deploy: "{{ install_root }}"
current_deploy: "{{ install_root }}"  # no current/past, just a single deploy
python_app_path: "{{ deploy }}"
python_venv_prompt: "prodigy"
# use pip install with special index url to install with the configured license
python_extra_packages:
  - prodigy>=1.18
python_extra_packages_pip_extra_args: "--extra-index-url https://{{ prodigy_license }}@download.prodi.gy"

application_db_name: 'cdh_prodigy'
application_dbuser_name: 'cdh_prodigy'
application_dbuser_password: "{{ vault_db_password }}"

# for nginx role
nginx_config_file: '/etc/nginx/nginx.conf'
running_on_server: true

# this application does not need NFS
nfs_enabled: false
# TODO: Investigate the issue with the TigerData mount
tigerdata_enabled: true

# NOTE: Currently need to upload these files manually to each server
prodigy_datafile: "{{ install_root }}/muse/data/notion-concept-tasks.jsonl"
prodigy_instruct: "{{ install_root }}/muse/data/instructions.html"

# Fetch annotation recipes from develop branch
prodigy_recipe_url: 'https://raw.githubusercontent.com/Princeton-CDH/muse/refs/heads/develop/src/muse/annotation/annotation_recipes.py'
prodigy_recipe_pyfile: "{{ install_root }}/muse/recipes/annotation_recipes.py"
# Optional: Fetch command recipes from develop branch
prodigy_commands_url: 'https://raw.githubusercontent.com/Princeton-CDH/muse/refs/heads/develop/src/muse/annotation/command_recipes.py'

# Current recipe options
prodigy_recipe: concept-eval
# Label for datat stored in database
prodigy_dataset: muse-concepts
prodigy_options: "{{ prodigy_recipe }} {{ prodigy_dataset }} {{ prodigy_datafile }} -F {{ prodigy_recipe_pyfile }} -I {{ prodigy_instruct }}"
# additional prodigy configurations to include in prodigy.json file
# values here takes precedence over the defaults in the role
prodigy_config_extra_options:
  - history_size: 3

# For setting shared and local Prodigy environment variables
prodigy_common_envs: 
  PRODIGY_CONFIG: "{{ install_root }}/prodigy.json"
  PRODIGY_DEPLOYED_URL: "{{ application_url }}"
  PRODIGY_LOGGING: "basic"
prodigy_local_envs:
  PRODIGY_ALLOWED_SESSIONS: "{{ vault_prodigy_sessions }}"
prodigy_envs: "{{ prodigy_common_envs | ansible.builtin.combine(prodigy_local_envs) }}"

# configure prodigy to run via supervisor
supervisor_programs:
  - name: 'prodigy'
    command: "{{ install_root }}/env/bin/python -m prodigy {{ prodigy_options }}"
    state: present
    configuration: |
      directory={{ install_root }}
      environment={% for name, value in prodigy_envs.items() %}{{ name }}="{{ value }}",{% endfor %}
      autostart=true
      autorestart=true
      startretries=1
      startsecs=1
      redirect_stderr=true
      stderr_logfile=/var/log/supervisor/{{ app_name }}-err.log
      stdout_logfile=/var/log/supervisor/{{ app_name }}-out.log
      user={{ deploy_user }}
      killasgroup=true
      stopasgroup=true

