---
# tasks to setup and configure an instance of Prodigy
- name: Ensure install root exists and deploy user has access
  tags:
    - setup
    - never
  become: true
  ansible.builtin.file:
    dest: "{{ install_root }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    state: directory
    recurse: no

- name: Ensure muse data and recipe directories exist with write permissions
  tags:
    - setup
    - never
  become: true
  ansible.builtin.file:
    path: "{{ item }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"
    state: directory
    mode: "0755"
  loop:
    - "{{ install_root }}/muse/recipes"
    - "{{ install_root }}/muse/data"

- name: Download Prodigy annotation recipes file
  become: true
  ansible.builtin.get_url:
    url: "{{ prodigy_recipe_url }}"
    dest: "{{ prodigy_recipe_pyfile }}"
    mode: '0755'

- name: Download Prodigy command recipes file
  become: true
  ansible.builtin.get_url:
    url: "{{ prodigy_commands_url }}"
    dest: "{{ install_root }}/muse/recipes"
    mode: "0755"
  when: prodigy_commands_url is defined

- name: Create requirements.txt for python requirements
  tags:
    - setup
    - never
  become: true
  ansible.builtin.copy:
    src: "requirements.txt"
    dest: "{{ install_root }}/requirements.txt"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Create Prodigy config file
  become: true
  ansible.builtin.copy:
    dest: "{{ install_root }}/prodigy.json"
    content: "{{ prodigy_config_options | combine(prodigy_config_extra_options) | to_json(indent=4) }}"
    owner: "{{ deploy_user }}"
    group: "{{ deploy_user }}"

- name: Setup nginx for prodigy assets
  tags:
    - setup
    - never
  block:
    - name: Run nginx as deploy user for access to tigerdata
      ansible.builtin.lineinfile:
        path: "{{ nginx_config_file }}"
        regexp: '^user '
        line: "user {{ deploy_user }};"
    - name: remove default nginx config
      ansible.builtin.file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
    - name: Install prodigy nginx site config
      ansible.builtin.template:
        src: prodigy_nginx_site.conf.j2
        dest: /etc/nginx/conf.d/prodigy.conf
        mode: 0644
      notify: "Restart Nginx"
