#!/bin/bash

# load shell configuration files if present, but don't error if they are not
[ -f ~/.bashrc ] && source ~/.bashrc
[ -f ~/.profile ] && source ~/.profile

# output date & time for logging
date

# run the passed command
exec "$@"