#!/bin/bash
# Check for unencrypted vault files and block commits

unencrypted=$(find . -name vault.yml -exec grep -L "\$ANSIBLE_VAULT" {} \;)

if [[ $unencrypted ]]; then
	echo -e "The following vault files are not encrypted:\n$unencrypted"
	exit 1
else
	exit 0
fi
