#!/bin/bash
# Check for unencrypted vault files and private keys
# Block commit if unencrypted

unencrypted=$(find . \( -name vault.yml -o -name id_rsa \) -exec grep -L "\$ANSIBLE_VAULT" {} \;)

if [[ $unencrypted ]]; then
	echo -e "The following files are not encrypted:\n$unencrypted"
	exit 1
else
	exit 0
fi
