---
# Runs the `compilemessages` command for compiling localized strings.
# https://docs.djangoproject.com/en/dev/ref/django-admin/#compilemessages

- name: Ensure gnu gettext is installed
  become: true
  tags:
    - setup
    - never
  ansible.builtin.apt:
    name: gettext
    state: present

- name: Compile localized messages
  become: true
  become_user: "{{ django_user }}"
  community.general.django_manage:
    command: compilemessages
    app_path: "{{ django_app_path }}"
    virtualenv: "{{ django_venv_path }}"
  environment:
    # Most CDH apps require the settings module to be explicitly set
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module | default('cdhweb.settings') }}"
    # Ensure the app code is in the python path so settings can be imported
    PYTHONPATH: "{{ django_app_path }}"
    # Force UTF-8 encoding for message files
    LANG: C.UTF-8
    LC_ALL: C.UTF-8
