###
# Staging specific configuration for Shakespeare and Company Project
###
---
running_on_server: true

# email prefix for staging error emails
email_prefix: '[S&co STAGING] '

# override passenger server name with staging hostname
application_url: "test-shakespeareandco.cdh.princeton.edu"

# passenger settings
passenger_server_name: "{{ application_url }}"

# source host when replicating data/media (from ansible host inventory file)
replication_source_host: shxco_production

# run cron jobs only on the first machine in the host group
cronjob_host: "cdh-test-shxco1.princeton.edu"

# configure scripts to run as cron jobs
crontab:

  # disable 100 years tweets for staging for now
  - name: "{{ django_app }} schedule 100 years tweets"
    minute: 30
    hour: 2
    job: "bin/cron-wrapper {{ deploy }}/env/bin/python {{ deploy }}/manage.py twitterbot_100years schedule  >> {{ logging_dir }}/twitterbot_100years.log  2>&1"
    state: absent

# solr settings
# shxco is using solr 9, so must override default staging solr 8 config
zk_host: "lib-zk-staging4:2181,lib-zk-staging5:2181,lib-zk-staging6:2181"
solr_url: "http://lib-solr9-staging.princeton.edu:8983/solr/"
solr_server: "{{ groups['solr9_staging'][0] }}"
solr_version: 9
# beyla
beyla_enabled: true
beyla_service_name: shxco
beyla_environment: staging
beyla_otlp_endpoint: "http://127.0.0.1:4318"
beyla_otlp_protocol: "http/protobuf"

beyla_open_ports:
  - 80
# signoz
otel_default_resource_attributes:
  host.name: "{{ inventory_hostname }}"
  service.name: shxco
  service.version: staging
  environment: staging

otel_receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 127.0.0.1:4317
      http:
        endpoint: 127.0.0.1:4318
  filelog/nginx-access:
    include: ["/var/log/nginx/access.log*"]
    start_at: end
    operators:
      - type: regex_parser
        regex: '^(?P<remote_addr>[^\s]+) \((?P<remote_user>[^)]*)\) - - \[(?P<time_local>[^\]]+)\] "(?P<method>\S+) (?P<path>\S+) (?P<protocol>[^"]+)" (?P<status>\d+) (?P<body_bytes_sent>\d+) "(?P<http_referer>[^"]*)" "(?P<http_user_agent>[^"]*)"'
        parse_from: body
      - type: time_parser
        parse_from: attributes.time_local
        layout_type: strptime
        layout: '%d/%b/%Y:%H:%M:%S %z'
      - type: add
        field: attributes.log_type
        value: "shxco_access"
      - type: add
        field: attributes.service_name
        value: shxco_access

  filelog/nginx-error:
    include: ["/var/log/nginx/error.log*"]
    start_at: end
    operators:
      - type: add
        field: attributes.log_type
        value: "shxco_error"
      - type: add
        field: attributes.service_name
        value: "shxco"

  hostmetrics:
    collection_interval: 30s
    scrapers:
      cpu: {}
      disk: {}
      filesystem: {}
      load: {}
      memory: {}
      network: {}

otel_processors:
  batch:
    send_batch_max_size: 1024
    send_batch_size: 512
    timeout: 30s

otel_exporters:
  loadbalancing:
    routing_key: service
    protocol:
      otlp:
        timeout: 10s
        tls:
          insecure: true
        sending_queue:
          enabled: true
          num_consumers: 10
          queue_size: 5000
        retry_on_failure:
          enabled: true
          initial_interval: 5s
          max_interval: 30s
          max_elapsed_time: 300s
    resolver:
      static:
        hostnames:
          - k8s-staging1.lib.princeton.edu:30374
          - k8s-staging2.lib.princeton.edu:30374
          - k8s-staging3.lib.princeton.edu:30374

  debug:
    verbosity: basic

otel_service_pipelines:
  logs:
    receivers:
      - filelog/nginx-access
      - filelog/nginx-error
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
      - debug

  metrics:
    receivers:
      - otlp
      - hostmetrics
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
      - debug

  traces:
    receivers:
      - otlp
    processors:
      - resource
      - batch
    exporters:
      - loadbalancing
