---
# by default this playbook runs in the staging environment
# to run in production, pass '-e runtime_env=production'
- name: build the cdh website
  hosts: cdhweb_{{ runtime_env | default('staging') }}
  # hosts: cdh-sandbox-web1.princeton.edu
  connection: ssh
  remote_user: pulsys
  become: true

  vars:
    # Define app-specific settings here
    # These will be passed into the generic django role
    django_settings_module: "cdhweb.settings.local_settings"
    django_venv_path: "/home/conan/venv"

  environment:
    PYTHONPATH: "{{ deploy | default(install_root) }}"
    DJANGO_SETTINGS_MODULE: "{{ django_settings_module }}"
    DJANGO_ENV: "{{ runtime_env | default('staging') }}"


  roles:
    - create_deployment
    - deploy_user
    - build_dependencies
    - build_project_repo
    - app_deploy
    - postgresql
    - passenger
    - build_npm
    - django
    - opencv_from_source
    - run_webpack   # requires font files from django task
    - finalize_deploy
    - close_deployment
