---
# by default this playbook runs in the staging environment
# to run in production, pass '-e runtime_env=production'
- name: build the cdh website
  hosts: cdhweb_{{ runtime_env | default('staging') }}
  connection: ssh
  remote_user: pulsys
  become: true
  roles:
    - role: pulibrary.princeton_ansible.otel_collector
    - role: pulibrary.princeton_ansible.beyla

    - create_deployment
    - deploy_user
    - build_dependencies
    - build_project_repo
    - postgresql
    - passenger
    - configure_logging
    - django
    - opencv_from_source
    - nodejs
    - finalize_deploy
    - close_deployment
