---
# by default this playbook runs in the staging environment
# to run in production, pass '-e runtime_env=production'
- name: Deploy and configure Prodigy web application
  hosts: prodigy_{{ runtime_env | default('staging') }}
  connection: ssh
  remote_user: pulsys
  become: true
  roles:
    - role: pulibrary.princeton_ansible.common
      tags:
        - common
    - role: pulibrary.princeton_ansible.otel_collector
      tags:
        - otel
    - role: pulibrary.princeton_ansible.beyla
      tags:
        - otel

    - deploy_user
    - postgresql
    - pulibrary.princeton_ansible.nginx
    - prodigy_setup
    - python
    - supervisor
  tasks:
    - name: Use supervisorctl to restart application
      ansible.builtin.command: "sudo supervisorctl restart prodigy"
